---
name: "CI"
on:
  # pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build
      - run: nix flake check
      - name: Login to ghcr
        shell: 'nix develop -c bash -e {0}'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | skopeo login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: nix run ".#push"
        env:
          REGISTRY: ghcr.io/voidlily
